for i in {1..4}; do cutadapt -g TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGTGCCAGCMGCCGCGGTAA -G GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGGACTACHVGGGTWTCTAAT \
-a ATTAGAWACCCBDGTAGTCCCTGTCTCTTATACACATCTCCGAGCCCACGAGAC -A TTACCGCGGCKGCTGGCACCTGTCTCTTATACACATCTGACGCTGCCGACGA \
-o output_${i}_R1.fastq -p output_${i}_R2.fastq sample_${i}.R1* sample_${i}.R2* \
--cores 4 --minimum-length 50 --discard-untrimmed ; done;
